### ISSUE TITLE
Error on Processing: this.processPageData is not a function

### ISSUE THREAD

**Issue by agent-z28** [ephraimm/n8n-nodes-google-document-ai#2]
In n8n v1.67.1 : I installed the [n8n-nodes-google-document-ai](https://github.com/ephraimm/n8n-nodes-google-document-ai) extension.

Actually i run into another Problem:

![image](https://github.com/user-attachments/assets/b6e9ef93-d398-4a61-860d-242180cc45e7)

This line seems to be not working:

https://github.com/ephraimm/n8n-nodes-google-document-ai/blob/master/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts#L206

http://localhost:5678/
Internal error
NodeOperationError: Internal error
    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-google-document-ai/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts:222:12)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:51
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20
this.processPageData is not a function
TypeError: this.processPageData is not a function
    at /home/node/.n8n/nodes/node_modules/n8n-nodes-google-document-ai/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts:206:53
    at Array.map (<anonymous>)
    at Object.execute (/home/node/.n8n/nodes/node_modules/n8n-nodes-google-document-ai/nodes/GoogleDocumentAI/GoogleDocumentAI.node.ts:206:29)
    at Workflow.runNode (/usr/local/lib/node_modules/n8n/node_modules/n8n-workflow/dist/Workflow.js:722:19)
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:704:51
    at /usr/local/lib/node_modules/n8n/node_modules/n8n-core/dist/WorkflowExecute.js:1134:20

**Comment by ephraimm** [comment]
for simplification, the node now uses @google-cloud/vision, review the readme for changes to auth.

The textDetection method on ImageAnnotatorClient returns textAnnotations which is returned as the out put of the node

**Comment by agent-z28** [comment]
> for simplification, the node now uses @google-cloud/vision, review the readme for changes to auth.
> 
> The textDetection method on ImageAnnotatorClient returns textAnnotations which is returned as the out put of the node




The code looks already much better.

would't it be better to use this?

https://cloud.google.com/nodejs/docs/reference/documentai/latest

npm install @google-cloud/documentai

**Comment by agent-z28** [comment]
@ephraimm the authentification works very good now :)!

**Comment by agent-z28** [comment]
@ephraimm we tested node-red https://nodered.org/

There are all those modules available + it's a real FOSS Licence. Therefor we switch.
